# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
  use_frameworks!


target 'Team-Tiger' do

  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyJSON'

  pod 'SnapKit', '0.30.0.beta2'

end
